spring:
  datasource:
    username: dbuser
    password: 258319TBlade!
    url: jdbc:mysql://localhost:3306/scucourse?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver