spring:
  datasource:
    username: DataUser
    password: 123456
    url: jdbc:mysql://localhost:3306/scucourse?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver